import 'package:flipcart_ui/models/my_account_list_model.dart';
import 'package:flutter/material.dart';

final List<MyAccountListItem> myUnauthenticatedAccountList = [
  MyAccountListItem(
    listId: 1,
    title: "My Account",
    hasCorrespondtitle: false,
    correspondtitle: "",
    subtitle: "",
    hasSubtitle: false,
    trailingText: "Sign in",
  ),
  MyAccountListItem(
    listId: 2,
    title: "Choose Language",
    hasCorrespondtitle: true,
    correspondtitle: "English",
    subtitle: "",
    hasSubtitle: false,
    trailingText: "CHOOSE LANGUAGE",
  ),
  MyAccountListItem(
    listId: 3,
    title: "My Whishlist",
    hasCorrespondtitle: false,
    correspondtitle: "",
    subtitle: "",
    hasSubtitle: false,
    trailingText: "VIEW YOUR WHISHILST",
  ),
];

final List<MyAccountListItem> myAuthenticatedAccountList = [
  MyAccountListItem(
    listId: 4,
    title: "Flipkart Plus",
    hasCorrespondtitle: false,
    correspondtitle: "",
    subtitle: "",
    hasSubtitle: false,
    trailingText: "VIEW PLUS ZONE",
  ),
  MyAccountListItem(
    listId: 5,
    title: "My Orders",
    hasCorrespondtitle: false,
    correspondtitle: "",
    subtitle: "",
    hasSubtitle: false,
    trailingText: "VIEW ALL ORDERS",
  ),
  MyAccountListItem(
    listId: 2,
    title: "Choose Language",
    hasCorrespondtitle: true,
    correspondtitle: "English",
    subtitle: "",
    hasSubtitle: false,
    trailingText: "CHOOSE LANGUAGE",
  ),
  MyAccountListItem(
    listId: 3,
    title: "My Whishlist",
    hasCorrespondtitle: false,
    correspondtitle: "",
    subtitle: "",
    hasSubtitle: false,
    trailingText: "VIEW YOUR WHISHILST",
  ),
  MyAccountListItem(
    listId: 6,
    title: "Flipkart Pay Later",
    hasCorrespondtitle: false,
    correspondtitle: "",
    subtitle: "Instant credit upto Rs 1 Lakh for all your shopping needs",
    hasSubtitle: true,
    trailingText: "APPLY NOW",
  ),
  MyAccountListItem(
    listId: 7,
    title: "Flipkart Creator Studio",
    hasCorrespondtitle: false,
    correspondtitle: "",
    subtitle:
        "Explore Flipkart Creator Studio, konw how to share your favourite products with your followers & earn moeny!",
    hasSubtitle: true,
    trailingText: "VIEW YOUR STUDIO",
  ),
  MyAccountListItem(
    listId: 8,
    title: "My Cards & Wallet",
    hasCorrespondtitle: true,
    correspondtitle: "\$0",
    subtitle: "",
    hasSubtitle: false,
    trailingText: "VIEW DETAILS",
  ),
  MyAccountListItem(
    listId: 9,
    title: "My Reviews",
    hasCorrespondtitle: false,
    correspondtitle: "",
    subtitle: "",
    hasSubtitle: false,
    trailingText: "VIEW YOUR REVIEWS",
  ),
  MyAccountListItem(
    listId: 10,
    title: "Refer & Earn",
    hasCorrespondtitle: false,
    correspondtitle: "",
    subtitle: "",
    hasSubtitle: false,
    trailingText: "VIEW DETAILS",
  ),
  MyAccountListItem(
    listId: 11,
    title: "My Questions & Answers",
    hasCorrespondtitle: false,
    correspondtitle: "",
    subtitle: "",
    hasSubtitle: false,
    trailingText: "VIEW YOUR Q&A",
  ),
  MyAccountListItem(
    listId: 12,
    title: "My Address",
    hasCorrespondtitle: false,
    correspondtitle: "",
    subtitle:
        "nani desad, gandevi dist-navsari, pin-396360, Gandevi, Gujarat - 396360",
    hasSubtitle: true,
    trailingText: "VIEW 2 MORE",
  ),
];

final List<MyAccountBelowListItem> belowAuthenticatedListItems = [
  MyAccountBelowListItem(
    listId: 1,
    title: "Notification Preference",
    hasLeadingIcon: true,
    hasMarginBelow: false,
    icon: Icons.notifications,
  ),
  MyAccountBelowListItem(
    listId: 2,
    title: "Account Settings",
    hasLeadingIcon: true,
    hasMarginBelow: true,
    icon: Icons.settings,
  ),
  MyAccountBelowListItem(
    listId: 3,
    title: "Help Centre",
    hasLeadingIcon: false,
    hasMarginBelow: false,
    icon: Icons.notifications,
  ),
  MyAccountBelowListItem(
    listId: 4,
    title: "Sell on Flipkart",
    hasLeadingIcon: false,
    icon: Icons.notifications,
    hasMarginBelow: false,
  ),
  MyAccountBelowListItem(
    listId: 5,
    title: "Legal",
    hasLeadingIcon: false,
    icon: Icons.notifications,
    hasMarginBelow: false,
  ),
  MyAccountBelowListItem(
    listId: 6,
    title: "Privacy Policy",
    hasLeadingIcon: false,
    hasMarginBelow: true,
    icon: Icons.notifications,
  ),
  MyAccountBelowListItem(
    listId: 7,
    title: "Logout of this app",
    hasLeadingIcon: true,
    icon: Icons.logout_sharp,
    hasMarginBelow: false,
  ),
  MyAccountBelowListItem(
    listId: 8,
    title: "Logout of all devices",
    hasLeadingIcon: true,
    icon: Icons.logout_sharp,
    hasMarginBelow: true,
  ),
];

final List<MyAccountBelowListItem> belowUnauthenticatedListItems = [
  MyAccountBelowListItem(
    listId: 1,
    title: "Notification Preference",
    hasLeadingIcon: true,
    hasMarginBelow: true,
    icon: Icons.notifications,
  ),
  MyAccountBelowListItem(
    listId: 3,
    title: "Help Centre",
    hasLeadingIcon: false,
    hasMarginBelow: false,
    icon: Icons.notifications,
  ),
  MyAccountBelowListItem(
    listId: 4,
    title: "Sell on Flipkart",
    hasLeadingIcon: false,
    icon: Icons.notifications,
    hasMarginBelow: false,
  ),
  MyAccountBelowListItem(
    listId: 5,
    title: "Legal",
    hasLeadingIcon: false,
    icon: Icons.notifications,
    hasMarginBelow: false,
  ),
  MyAccountBelowListItem(
    listId: 6,
    title: "Privacy Policy",
    hasLeadingIcon: false,
    hasMarginBelow: true,
    icon: Icons.notifications,
  ),
];
